version: "3.7"

services:
  nginx:
    container_name: "test-nginx"
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    links:
      - php-fpm
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm
    networks:
      - test-network

  php-fpm:
    container_name: "test-php-fpm"
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - test-network

  mysql:
    container_name: "test-mysql"
    image: mysql:5.7.28
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    networks:
      - test-network

networks:
  test-network:
